// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPC.proto

#include "RPC.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace RPC {
class CreateInstanceParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CreateInstanceParam>
      _instance;
} _CreateInstanceParam_default_instance_;
class VariantParamDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VariantParam>
      _instance;
  ::google::protobuf::uint32 fixed32_;
  ::google::protobuf::int32 sfixed32_;
  ::google::protobuf::uint64 fixed64_;
  ::google::protobuf::int64 sfixed64_;
  bool bool__;
  float float__;
  double double__;
  ::google::protobuf::internal::ArenaStringPtr string_;
  ::google::protobuf::internal::ArenaStringPtr decimal_;
  ::google::protobuf::internal::ArenaStringPtr bytes_;
  ::google::protobuf::internal::ArenaStringPtr guid_;
} _VariantParam_default_instance_;
class RpcInvokeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RpcInvoke>
      _instance;
} _RpcInvoke_default_instance_;
class RpcReturn_ExceptionInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RpcReturn_ExceptionInfo>
      _instance;
} _RpcReturn_ExceptionInfo_default_instance_;
class RpcReturnDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RpcReturn>
      _instance;
} _RpcReturn_default_instance_;
}  // namespace RPC
namespace protobuf_RPC_2eproto {
void InitDefaultsCreateInstanceParamImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::RPC::_CreateInstanceParam_default_instance_;
    new (ptr) ::RPC::CreateInstanceParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RPC::CreateInstanceParam::InitAsDefaultInstance();
}

void InitDefaultsCreateInstanceParam() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCreateInstanceParamImpl);
}

void InitDefaultsVariantParamImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::RPC::_VariantParam_default_instance_;
    new (ptr) ::RPC::VariantParam();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RPC::VariantParam::InitAsDefaultInstance();
}

void InitDefaultsVariantParam() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsVariantParamImpl);
}

void InitDefaultsRpcInvokeImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_RPC_2eproto::InitDefaultsVariantParam();
  {
    void* ptr = &::RPC::_RpcInvoke_default_instance_;
    new (ptr) ::RPC::RpcInvoke();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RPC::RpcInvoke::InitAsDefaultInstance();
}

void InitDefaultsRpcInvoke() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsRpcInvokeImpl);
}

void InitDefaultsRpcReturn_ExceptionInfoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::RPC::_RpcReturn_ExceptionInfo_default_instance_;
    new (ptr) ::RPC::RpcReturn_ExceptionInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RPC::RpcReturn_ExceptionInfo::InitAsDefaultInstance();
}

void InitDefaultsRpcReturn_ExceptionInfo() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsRpcReturn_ExceptionInfoImpl);
}

void InitDefaultsRpcReturnImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_RPC_2eproto::InitDefaultsVariantParam();
  protobuf_RPC_2eproto::InitDefaultsRpcReturn_ExceptionInfo();
  {
    void* ptr = &::RPC::_RpcReturn_default_instance_;
    new (ptr) ::RPC::RpcReturn();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RPC::RpcReturn::InitAsDefaultInstance();
}

void InitDefaultsRpcReturn() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsRpcReturnImpl);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::CreateInstanceParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::CreateInstanceParam, version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::CreateInstanceParam, activityid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::CreateInstanceParam, guid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::VariantParam, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::VariantParam, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::RPC::VariantParamDefaultTypeInternal, fixed32_),
  offsetof(::RPC::VariantParamDefaultTypeInternal, sfixed32_),
  offsetof(::RPC::VariantParamDefaultTypeInternal, fixed64_),
  offsetof(::RPC::VariantParamDefaultTypeInternal, sfixed64_),
  offsetof(::RPC::VariantParamDefaultTypeInternal, bool__),
  offsetof(::RPC::VariantParamDefaultTypeInternal, float__),
  offsetof(::RPC::VariantParamDefaultTypeInternal, double__),
  offsetof(::RPC::VariantParamDefaultTypeInternal, string_),
  offsetof(::RPC::VariantParamDefaultTypeInternal, decimal_),
  offsetof(::RPC::VariantParamDefaultTypeInternal, bytes_),
  offsetof(::RPC::VariantParamDefaultTypeInternal, guid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::VariantParam, Value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcInvoke, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcInvoke, objectid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcInvoke, interfaceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcInvoke, callid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcInvoke, dispid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcInvoke, wflags_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcInvoke, params_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn_ExceptionInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn_ExceptionInfo, description_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn_ExceptionInfo, scode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn_ExceptionInfo, wcode_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn, callid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn, hresult_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn, ref_out_params_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RPC::RpcReturn, exception_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::RPC::CreateInstanceParam)},
  { 8, -1, sizeof(::RPC::VariantParam)},
  { 25, -1, sizeof(::RPC::RpcInvoke)},
  { 36, -1, sizeof(::RPC::RpcReturn_ExceptionInfo)},
  { 44, -1, sizeof(::RPC::RpcReturn)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::RPC::_CreateInstanceParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::RPC::_VariantParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::RPC::_RpcInvoke_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::RPC::_RpcReturn_ExceptionInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::RPC::_RpcReturn_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "RPC.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\tRPC.proto\022\003RPC\"H\n\023CreateInstanceParam\022"
      "\017\n\007Version\030\001 \001(\007\022\022\n\nActivityID\030\002 \001(\007\022\014\n\004"
      "Guid\030\003 \001(\t\"\336\001\n\014VariantParam\022\021\n\007Fixed32\030\001"
      " \001(\007H\000\022\022\n\010SFixed32\030\002 \001(\017H\000\022\021\n\007Fixed64\030\003 "
      "\001(\006H\000\022\022\n\010SFixed64\030\004 \001(\020H\000\022\016\n\004Bool\030\005 \001(\010H"
      "\000\022\017\n\005Float\030\006 \001(\002H\000\022\020\n\006Double\030\007 \001(\001H\000\022\020\n\006"
      "String\030\010 \001(\tH\000\022\021\n\007Decimal\030\t \001(\tH\000\022\017\n\005Byt"
      "es\030\n \001(\014H\000\022\016\n\004Guid\030\013 \001(\014H\000B\007\n\005Value\"\205\001\n\t"
      "RpcInvoke\022\020\n\010ObjectID\030\001 \001(\017\022\023\n\013Interface"
      "ID\030\002 \001(\007\022\016\n\006CallID\030\003 \001(\017\022\016\n\006DispID\030\004 \001(\005"
      "\022\016\n\006wFlags\030\005 \001(\005\022!\n\006Params\030\006 \003(\0132\021.RPC.V"
      "ariantParam\"\314\001\n\tRpcReturn\022\016\n\006CallID\030\001 \001("
      "\017\022\017\n\007HResult\030\002 \001(\017\022)\n\016Ref_Out_Params\030\003 \003"
      "(\0132\021.RPC.VariantParam\022/\n\tException\030\004 \001(\013"
      "2\034.RPC.RpcReturn.ExceptionInfo\032B\n\rExcept"
      "ionInfo\022\023\n\013Description\030\001 \001(\t\022\r\n\005scode\030\002 "
      "\001(\005\022\r\n\005wCode\030\003 \001(\0052\024\n\022RemoteClassFactory"
      "B\002H\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 692);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RPC.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_RPC_2eproto
namespace RPC {

// ===================================================================

void CreateInstanceParam::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CreateInstanceParam::kVersionFieldNumber;
const int CreateInstanceParam::kActivityIDFieldNumber;
const int CreateInstanceParam::kGuidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CreateInstanceParam::CreateInstanceParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_RPC_2eproto::InitDefaultsCreateInstanceParam();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.CreateInstanceParam)
}
CreateInstanceParam::CreateInstanceParam(const CreateInstanceParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.guid().size() > 0) {
    guid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.guid_);
  }
  ::memcpy(&version_, &from.version_,
    static_cast<size_t>(reinterpret_cast<char*>(&activityid_) -
    reinterpret_cast<char*>(&version_)) + sizeof(activityid_));
  // @@protoc_insertion_point(copy_constructor:RPC.CreateInstanceParam)
}

void CreateInstanceParam::SharedCtor() {
  guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&version_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&activityid_) -
      reinterpret_cast<char*>(&version_)) + sizeof(activityid_));
  _cached_size_ = 0;
}

CreateInstanceParam::~CreateInstanceParam() {
  // @@protoc_insertion_point(destructor:RPC.CreateInstanceParam)
  SharedDtor();
}

void CreateInstanceParam::SharedDtor() {
  guid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CreateInstanceParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CreateInstanceParam::descriptor() {
  ::protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CreateInstanceParam& CreateInstanceParam::default_instance() {
  ::protobuf_RPC_2eproto::InitDefaultsCreateInstanceParam();
  return *internal_default_instance();
}

CreateInstanceParam* CreateInstanceParam::New(::google::protobuf::Arena* arena) const {
  CreateInstanceParam* n = new CreateInstanceParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CreateInstanceParam::Swap(CreateInstanceParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CreateInstanceParam::InternalSwap(CreateInstanceParam* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CreateInstanceParam::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void VariantParam::InitAsDefaultInstance() {
  ::RPC::_VariantParam_default_instance_.fixed32_ = 0u;
  ::RPC::_VariantParam_default_instance_.sfixed32_ = 0;
  ::RPC::_VariantParam_default_instance_.fixed64_ = GOOGLE_ULONGLONG(0);
  ::RPC::_VariantParam_default_instance_.sfixed64_ = GOOGLE_LONGLONG(0);
  ::RPC::_VariantParam_default_instance_.bool__ = false;
  ::RPC::_VariantParam_default_instance_.float__ = 0;
  ::RPC::_VariantParam_default_instance_.double__ = 0;
  ::RPC::_VariantParam_default_instance_.string_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::RPC::_VariantParam_default_instance_.decimal_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::RPC::_VariantParam_default_instance_.bytes_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::RPC::_VariantParam_default_instance_.guid_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VariantParam::kFixed32FieldNumber;
const int VariantParam::kSFixed32FieldNumber;
const int VariantParam::kFixed64FieldNumber;
const int VariantParam::kSFixed64FieldNumber;
const int VariantParam::kBoolFieldNumber;
const int VariantParam::kFloatFieldNumber;
const int VariantParam::kDoubleFieldNumber;
const int VariantParam::kStringFieldNumber;
const int VariantParam::kDecimalFieldNumber;
const int VariantParam::kBytesFieldNumber;
const int VariantParam::kGuidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VariantParam::VariantParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_RPC_2eproto::InitDefaultsVariantParam();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.VariantParam)
}
VariantParam::VariantParam(const VariantParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_Value();
  switch (from.Value_case()) {
    case kFixed32: {
      set_fixed32(from.fixed32());
      break;
    }
    case kSFixed32: {
      set_sfixed32(from.sfixed32());
      break;
    }
    case kFixed64: {
      set_fixed64(from.fixed64());
      break;
    }
    case kSFixed64: {
      set_sfixed64(from.sfixed64());
      break;
    }
    case kBool: {
      set_bool_(from.bool_());
      break;
    }
    case kFloat: {
      set_float_(from.float_());
      break;
    }
    case kDouble: {
      set_double_(from.double_());
      break;
    }
    case kString: {
      set_string(from.string());
      break;
    }
    case kDecimal: {
      set_decimal(from.decimal());
      break;
    }
    case kBytes: {
      set_bytes(from.bytes());
      break;
    }
    case kGuid: {
      set_guid(from.guid());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:RPC.VariantParam)
}

void VariantParam::SharedCtor() {
  clear_has_Value();
  _cached_size_ = 0;
}

VariantParam::~VariantParam() {
  // @@protoc_insertion_point(destructor:RPC.VariantParam)
  SharedDtor();
}

void VariantParam::SharedDtor() {
  if (has_Value()) {
    clear_Value();
  }
}

void VariantParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VariantParam::descriptor() {
  ::protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VariantParam& VariantParam::default_instance() {
  ::protobuf_RPC_2eproto::InitDefaultsVariantParam();
  return *internal_default_instance();
}

VariantParam* VariantParam::New(::google::protobuf::Arena* arena) const {
  VariantParam* n = new VariantParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VariantParam::clear_Value() {
// @@protoc_insertion_point(one_of_clear_start:RPC.VariantParam)
  switch (Value_case()) {
    case kFixed32: {
      // No need to clear
      break;
    }
    case kSFixed32: {
      // No need to clear
      break;
    }
    case kFixed64: {
      // No need to clear
      break;
    }
    case kSFixed64: {
      // No need to clear
      break;
    }
    case kBool: {
      // No need to clear
      break;
    }
    case kFloat: {
      // No need to clear
      break;
    }
    case kDouble: {
      // No need to clear
      break;
    }
    case kString: {
      Value_.string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kDecimal: {
      Value_.decimal_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kBytes: {
      Value_.bytes_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kGuid: {
      Value_.guid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = VALUE_NOT_SET;
}


void VariantParam::Swap(VariantParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VariantParam::InternalSwap(VariantParam* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata VariantParam::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RpcInvoke::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcInvoke::kObjectIDFieldNumber;
const int RpcInvoke::kInterfaceIDFieldNumber;
const int RpcInvoke::kCallIDFieldNumber;
const int RpcInvoke::kDispIDFieldNumber;
const int RpcInvoke::kWFlagsFieldNumber;
const int RpcInvoke::kParamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcInvoke::RpcInvoke()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_RPC_2eproto::InitDefaultsRpcInvoke();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.RpcInvoke)
}
RpcInvoke::RpcInvoke(const RpcInvoke& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      params_(from.params_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&objectid_, &from.objectid_,
    static_cast<size_t>(reinterpret_cast<char*>(&wflags_) -
    reinterpret_cast<char*>(&objectid_)) + sizeof(wflags_));
  // @@protoc_insertion_point(copy_constructor:RPC.RpcInvoke)
}

void RpcInvoke::SharedCtor() {
  ::memset(&objectid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&wflags_) -
      reinterpret_cast<char*>(&objectid_)) + sizeof(wflags_));
  _cached_size_ = 0;
}

RpcInvoke::~RpcInvoke() {
  // @@protoc_insertion_point(destructor:RPC.RpcInvoke)
  SharedDtor();
}

void RpcInvoke::SharedDtor() {
}

void RpcInvoke::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcInvoke::descriptor() {
  ::protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RpcInvoke& RpcInvoke::default_instance() {
  ::protobuf_RPC_2eproto::InitDefaultsRpcInvoke();
  return *internal_default_instance();
}

RpcInvoke* RpcInvoke::New(::google::protobuf::Arena* arena) const {
  RpcInvoke* n = new RpcInvoke;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcInvoke::Swap(RpcInvoke* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcInvoke::InternalSwap(RpcInvoke* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RpcInvoke::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RpcReturn_ExceptionInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcReturn_ExceptionInfo::kDescriptionFieldNumber;
const int RpcReturn_ExceptionInfo::kScodeFieldNumber;
const int RpcReturn_ExceptionInfo::kWCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcReturn_ExceptionInfo::RpcReturn_ExceptionInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_RPC_2eproto::InitDefaultsRpcReturn_ExceptionInfo();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.RpcReturn.ExceptionInfo)
}
RpcReturn_ExceptionInfo::RpcReturn_ExceptionInfo(const RpcReturn_ExceptionInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.description().size() > 0) {
    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  ::memcpy(&scode_, &from.scode_,
    static_cast<size_t>(reinterpret_cast<char*>(&wcode_) -
    reinterpret_cast<char*>(&scode_)) + sizeof(wcode_));
  // @@protoc_insertion_point(copy_constructor:RPC.RpcReturn.ExceptionInfo)
}

void RpcReturn_ExceptionInfo::SharedCtor() {
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&scode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&wcode_) -
      reinterpret_cast<char*>(&scode_)) + sizeof(wcode_));
  _cached_size_ = 0;
}

RpcReturn_ExceptionInfo::~RpcReturn_ExceptionInfo() {
  // @@protoc_insertion_point(destructor:RPC.RpcReturn.ExceptionInfo)
  SharedDtor();
}

void RpcReturn_ExceptionInfo::SharedDtor() {
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RpcReturn_ExceptionInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcReturn_ExceptionInfo::descriptor() {
  ::protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RpcReturn_ExceptionInfo& RpcReturn_ExceptionInfo::default_instance() {
  ::protobuf_RPC_2eproto::InitDefaultsRpcReturn_ExceptionInfo();
  return *internal_default_instance();
}

RpcReturn_ExceptionInfo* RpcReturn_ExceptionInfo::New(::google::protobuf::Arena* arena) const {
  RpcReturn_ExceptionInfo* n = new RpcReturn_ExceptionInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcReturn_ExceptionInfo::Swap(RpcReturn_ExceptionInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcReturn_ExceptionInfo::InternalSwap(RpcReturn_ExceptionInfo* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RpcReturn_ExceptionInfo::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RpcReturn::InitAsDefaultInstance() {
  ::RPC::_RpcReturn_default_instance_._instance.get_mutable()->exception_ = const_cast< ::RPC::RpcReturn_ExceptionInfo*>(
      ::RPC::RpcReturn_ExceptionInfo::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcReturn::kCallIDFieldNumber;
const int RpcReturn::kHResultFieldNumber;
const int RpcReturn::kRefOutParamsFieldNumber;
const int RpcReturn::kExceptionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcReturn::RpcReturn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_RPC_2eproto::InitDefaultsRpcReturn();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.RpcReturn)
}
RpcReturn::RpcReturn(const RpcReturn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      ref_out_params_(from.ref_out_params_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_exception()) {
    exception_ = new ::RPC::RpcReturn_ExceptionInfo(*from.exception_);
  } else {
    exception_ = NULL;
  }
  ::memcpy(&callid_, &from.callid_,
    static_cast<size_t>(reinterpret_cast<char*>(&hresult_) -
    reinterpret_cast<char*>(&callid_)) + sizeof(hresult_));
  // @@protoc_insertion_point(copy_constructor:RPC.RpcReturn)
}

void RpcReturn::SharedCtor() {
  ::memset(&exception_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&hresult_) -
      reinterpret_cast<char*>(&exception_)) + sizeof(hresult_));
  _cached_size_ = 0;
}

RpcReturn::~RpcReturn() {
  // @@protoc_insertion_point(destructor:RPC.RpcReturn)
  SharedDtor();
}

void RpcReturn::SharedDtor() {
  if (this != internal_default_instance()) delete exception_;
}

void RpcReturn::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcReturn::descriptor() {
  ::protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RpcReturn& RpcReturn::default_instance() {
  ::protobuf_RPC_2eproto::InitDefaultsRpcReturn();
  return *internal_default_instance();
}

RpcReturn* RpcReturn::New(::google::protobuf::Arena* arena) const {
  RpcReturn* n = new RpcReturn;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcReturn::Swap(RpcReturn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcReturn::InternalSwap(RpcReturn* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RpcReturn::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_RPC_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace RPC

// @@protoc_insertion_point(global_scope)
