// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPC.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "RPC.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace RPC {
class CreateInstanceParamDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CreateInstanceParam> {
} _CreateInstanceParam_default_instance_;
class VariantParamDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<VariantParam> {
  public:
  ::google::protobuf::uint32 fixed32_;
  ::google::protobuf::int32 sfixed32_;
  ::google::protobuf::uint64 fixed64_;
  ::google::protobuf::int64 sfixed64_;
  bool bool__;
  float float__;
  double double__;
  ::google::protobuf::internal::ArenaStringPtr string_;
  ::google::protobuf::internal::ArenaStringPtr decimal_;
  ::google::protobuf::internal::ArenaStringPtr bytes_;
  ::google::protobuf::internal::ArenaStringPtr guid_;
} _VariantParam_default_instance_;
class RpcInvokeDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<RpcInvoke> {
} _RpcInvoke_default_instance_;
class RpcReturn_ExceptionInfoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<RpcReturn_ExceptionInfo> {
} _RpcReturn_ExceptionInfo_default_instance_;
class RpcReturnDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<RpcReturn> {
} _RpcReturn_default_instance_;

namespace protobuf_RPC_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[5];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateInstanceParam, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateInstanceParam, version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateInstanceParam, activityid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CreateInstanceParam, guid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VariantParam, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VariantParam, _oneof_case_[0]),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), fixed32_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), sfixed32_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), fixed64_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), sfixed64_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), bool__),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), float__),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), double__),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), string_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), decimal_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), bytes_),
  PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET((&_VariantParam_default_instance_), guid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VariantParam, Value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcInvoke, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcInvoke, proxyid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcInvoke, interfaceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcInvoke, callid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcInvoke, dispid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcInvoke, wflags_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcInvoke, params_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn_ExceptionInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn_ExceptionInfo, description_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn_ExceptionInfo, scode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn_ExceptionInfo, wcode_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn, callid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn, hresult_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn, returnval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcReturn, exception_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CreateInstanceParam)},
  { 7, -1, sizeof(VariantParam)},
  { 23, -1, sizeof(RpcInvoke)},
  { 33, -1, sizeof(RpcReturn_ExceptionInfo)},
  { 40, -1, sizeof(RpcReturn)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CreateInstanceParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_VariantParam_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RpcInvoke_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RpcReturn_ExceptionInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_RpcReturn_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "RPC.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

}  // namespace

void TableStruct::Shutdown() {
  _CreateInstanceParam_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _VariantParam_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _RpcInvoke_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _RpcReturn_ExceptionInfo_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _RpcReturn_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CreateInstanceParam_default_instance_.DefaultConstruct();
  _VariantParam_default_instance_.DefaultConstruct();
  _RpcInvoke_default_instance_.DefaultConstruct();
  _RpcReturn_ExceptionInfo_default_instance_.DefaultConstruct();
  _RpcReturn_default_instance_.DefaultConstruct();
  _VariantParam_default_instance_.fixed32_ = 0u;
  _VariantParam_default_instance_.sfixed32_ = 0;
  _VariantParam_default_instance_.fixed64_ = GOOGLE_ULONGLONG(0);
  _VariantParam_default_instance_.sfixed64_ = GOOGLE_LONGLONG(0);
  _VariantParam_default_instance_.bool__ = false;
  _VariantParam_default_instance_.float__ = 0;
  _VariantParam_default_instance_.double__ = 0;
  _VariantParam_default_instance_.string_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _VariantParam_default_instance_.decimal_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _VariantParam_default_instance_.bytes_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _VariantParam_default_instance_.guid_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _RpcReturn_default_instance_.get_mutable()->returnval_ = const_cast< ::RPC::VariantParam*>(
      ::RPC::VariantParam::internal_default_instance());
  _RpcReturn_default_instance_.get_mutable()->exception_ = const_cast< ::RPC::RpcReturn_ExceptionInfo*>(
      ::RPC::RpcReturn_ExceptionInfo::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\tRPC.proto\022\003RPC\"H\n\023CreateInstanceParam\022"
      "\017\n\007Version\030\001 \001(\007\022\022\n\nActivityID\030\002 \001(\007\022\014\n\004"
      "Guid\030\003 \001(\t\"\336\001\n\014VariantParam\022\021\n\007Fixed32\030\001"
      " \001(\007H\000\022\022\n\010SFixed32\030\002 \001(\017H\000\022\021\n\007Fixed64\030\003 "
      "\001(\006H\000\022\022\n\010SFixed64\030\004 \001(\020H\000\022\016\n\004Bool\030\005 \001(\010H"
      "\000\022\017\n\005Float\030\006 \001(\002H\000\022\020\n\006Double\030\007 \001(\001H\000\022\020\n\006"
      "String\030\010 \001(\tH\000\022\021\n\007Decimal\030\t \001(\tH\000\022\017\n\005Byt"
      "es\030\n \001(\014H\000\022\016\n\004Guid\030\013 \001(\014H\000B\007\n\005Value\"\204\001\n\t"
      "RpcInvoke\022\017\n\007ProxyID\030\001 \001(\017\022\023\n\013InterfaceI"
      "D\030\002 \001(\007\022\016\n\006CallID\030\003 \001(\017\022\016\n\006DispID\030\004 \001(\005\022"
      "\016\n\006wFlags\030\005 \001(\005\022!\n\006Params\030\006 \003(\0132\021.RPC.Va"
      "riantParam\"\307\001\n\tRpcReturn\022\016\n\006CallID\030\001 \001(\017"
      "\022\017\n\007HResult\030\002 \001(\017\022$\n\tReturnVal\030\003 \001(\0132\021.R"
      "PC.VariantParam\022/\n\tException\030\004 \001(\0132\034.RPC"
      ".RpcReturn.ExceptionInfo\032B\n\rExceptionInf"
      "o\022\023\n\013Description\030\001 \001(\t\022\r\n\005scode\030\002 \001(\005\022\r\n"
      "\005wCode\030\003 \001(\0052\024\n\022RemoteClassFactoryB\002H\002b\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 686);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "RPC.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_RPC_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CreateInstanceParam::kVersionFieldNumber;
const int CreateInstanceParam::kActivityIDFieldNumber;
const int CreateInstanceParam::kGuidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CreateInstanceParam::CreateInstanceParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RPC_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.CreateInstanceParam)
}
CreateInstanceParam::CreateInstanceParam(const CreateInstanceParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.guid().size() > 0) {
    guid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.guid_);
  }
  ::memcpy(&version_, &from.version_,
    reinterpret_cast<char*>(&activityid_) -
    reinterpret_cast<char*>(&version_) + sizeof(activityid_));
  // @@protoc_insertion_point(copy_constructor:RPC.CreateInstanceParam)
}

void CreateInstanceParam::SharedCtor() {
  guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&version_, 0, reinterpret_cast<char*>(&activityid_) -
    reinterpret_cast<char*>(&version_) + sizeof(activityid_));
  _cached_size_ = 0;
}

CreateInstanceParam::~CreateInstanceParam() {
  // @@protoc_insertion_point(destructor:RPC.CreateInstanceParam)
  SharedDtor();
}

void CreateInstanceParam::SharedDtor() {
  guid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CreateInstanceParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CreateInstanceParam::descriptor() {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[0].descriptor;
}

const CreateInstanceParam& CreateInstanceParam::default_instance() {
  protobuf_RPC_2eproto::InitDefaults();
  return *internal_default_instance();
}

CreateInstanceParam* CreateInstanceParam::New(::google::protobuf::Arena* arena) const {
  CreateInstanceParam* n = new CreateInstanceParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CreateInstanceParam::Swap(CreateInstanceParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CreateInstanceParam::InternalSwap(CreateInstanceParam* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata CreateInstanceParam::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CreateInstanceParam

// fixed32 Version = 1;
void CreateInstanceParam::clear_version() {
  version_ = 0u;
}
::google::protobuf::uint32 CreateInstanceParam::version() const {
  // @@protoc_insertion_point(field_get:RPC.CreateInstanceParam.Version)
  return version_;
}
void CreateInstanceParam::set_version(::google::protobuf::uint32 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:RPC.CreateInstanceParam.Version)
}

// fixed32 ActivityID = 2;
void CreateInstanceParam::clear_activityid() {
  activityid_ = 0u;
}
::google::protobuf::uint32 CreateInstanceParam::activityid() const {
  // @@protoc_insertion_point(field_get:RPC.CreateInstanceParam.ActivityID)
  return activityid_;
}
void CreateInstanceParam::set_activityid(::google::protobuf::uint32 value) {
  
  activityid_ = value;
  // @@protoc_insertion_point(field_set:RPC.CreateInstanceParam.ActivityID)
}

// string Guid = 3;
void CreateInstanceParam::clear_guid() {
  guid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CreateInstanceParam::guid() const {
  // @@protoc_insertion_point(field_get:RPC.CreateInstanceParam.Guid)
  return guid_.GetNoArena();
}
void CreateInstanceParam::set_guid(const ::std::string& value) {
  
  guid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPC.CreateInstanceParam.Guid)
}
#if LANG_CXX11
void CreateInstanceParam::set_guid(::std::string&& value) {
  
  guid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPC.CreateInstanceParam.Guid)
}
#endif
void CreateInstanceParam::set_guid(const char* value) {
  
  guid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPC.CreateInstanceParam.Guid)
}
void CreateInstanceParam::set_guid(const char* value, size_t size) {
  
  guid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPC.CreateInstanceParam.Guid)
}
::std::string* CreateInstanceParam::mutable_guid() {
  
  // @@protoc_insertion_point(field_mutable:RPC.CreateInstanceParam.Guid)
  return guid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CreateInstanceParam::release_guid() {
  // @@protoc_insertion_point(field_release:RPC.CreateInstanceParam.Guid)
  
  return guid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CreateInstanceParam::set_allocated_guid(::std::string* guid) {
  if (guid != NULL) {
    
  } else {
    
  }
  guid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), guid);
  // @@protoc_insertion_point(field_set_allocated:RPC.CreateInstanceParam.Guid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VariantParam::kFixed32FieldNumber;
const int VariantParam::kSFixed32FieldNumber;
const int VariantParam::kFixed64FieldNumber;
const int VariantParam::kSFixed64FieldNumber;
const int VariantParam::kBoolFieldNumber;
const int VariantParam::kFloatFieldNumber;
const int VariantParam::kDoubleFieldNumber;
const int VariantParam::kStringFieldNumber;
const int VariantParam::kDecimalFieldNumber;
const int VariantParam::kBytesFieldNumber;
const int VariantParam::kGuidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VariantParam::VariantParam()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RPC_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.VariantParam)
}
VariantParam::VariantParam(const VariantParam& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_Value();
  switch (from.Value_case()) {
    case kFixed32: {
      set_fixed32(from.fixed32());
      break;
    }
    case kSFixed32: {
      set_sfixed32(from.sfixed32());
      break;
    }
    case kFixed64: {
      set_fixed64(from.fixed64());
      break;
    }
    case kSFixed64: {
      set_sfixed64(from.sfixed64());
      break;
    }
    case kBool: {
      set_bool_(from.bool_());
      break;
    }
    case kFloat: {
      set_float_(from.float_());
      break;
    }
    case kDouble: {
      set_double_(from.double_());
      break;
    }
    case kString: {
      set_string(from.string());
      break;
    }
    case kDecimal: {
      set_decimal(from.decimal());
      break;
    }
    case kBytes: {
      set_bytes(from.bytes());
      break;
    }
    case kGuid: {
      set_guid(from.guid());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:RPC.VariantParam)
}

void VariantParam::SharedCtor() {
  clear_has_Value();
  _cached_size_ = 0;
}

VariantParam::~VariantParam() {
  // @@protoc_insertion_point(destructor:RPC.VariantParam)
  SharedDtor();
}

void VariantParam::SharedDtor() {
  if (has_Value()) {
    clear_Value();
  }
}

void VariantParam::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VariantParam::descriptor() {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[1].descriptor;
}

const VariantParam& VariantParam::default_instance() {
  protobuf_RPC_2eproto::InitDefaults();
  return *internal_default_instance();
}

VariantParam* VariantParam::New(::google::protobuf::Arena* arena) const {
  VariantParam* n = new VariantParam;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VariantParam::clear_Value() {
// @@protoc_insertion_point(one_of_clear_start:RPC.VariantParam)
  switch (Value_case()) {
    case kFixed32: {
      // No need to clear
      break;
    }
    case kSFixed32: {
      // No need to clear
      break;
    }
    case kFixed64: {
      // No need to clear
      break;
    }
    case kSFixed64: {
      // No need to clear
      break;
    }
    case kBool: {
      // No need to clear
      break;
    }
    case kFloat: {
      // No need to clear
      break;
    }
    case kDouble: {
      // No need to clear
      break;
    }
    case kString: {
      Value_.string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kDecimal: {
      Value_.decimal_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kBytes: {
      Value_.bytes_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kGuid: {
      Value_.guid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = VALUE_NOT_SET;
}


void VariantParam::Swap(VariantParam* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VariantParam::InternalSwap(VariantParam* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata VariantParam::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// VariantParam

// fixed32 Fixed32 = 1;
bool VariantParam::has_fixed32() const {
  return Value_case() == kFixed32;
}
void VariantParam::set_has_fixed32() {
  _oneof_case_[0] = kFixed32;
}
void VariantParam::clear_fixed32() {
  if (has_fixed32()) {
    Value_.fixed32_ = 0u;
    clear_has_Value();
  }
}
::google::protobuf::uint32 VariantParam::fixed32() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Fixed32)
  if (has_fixed32()) {
    return Value_.fixed32_;
  }
  return 0u;
}
void VariantParam::set_fixed32(::google::protobuf::uint32 value) {
  if (!has_fixed32()) {
    clear_Value();
    set_has_fixed32();
  }
  Value_.fixed32_ = value;
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Fixed32)
}

// sfixed32 SFixed32 = 2;
bool VariantParam::has_sfixed32() const {
  return Value_case() == kSFixed32;
}
void VariantParam::set_has_sfixed32() {
  _oneof_case_[0] = kSFixed32;
}
void VariantParam::clear_sfixed32() {
  if (has_sfixed32()) {
    Value_.sfixed32_ = 0;
    clear_has_Value();
  }
}
::google::protobuf::int32 VariantParam::sfixed32() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.SFixed32)
  if (has_sfixed32()) {
    return Value_.sfixed32_;
  }
  return 0;
}
void VariantParam::set_sfixed32(::google::protobuf::int32 value) {
  if (!has_sfixed32()) {
    clear_Value();
    set_has_sfixed32();
  }
  Value_.sfixed32_ = value;
  // @@protoc_insertion_point(field_set:RPC.VariantParam.SFixed32)
}

// fixed64 Fixed64 = 3;
bool VariantParam::has_fixed64() const {
  return Value_case() == kFixed64;
}
void VariantParam::set_has_fixed64() {
  _oneof_case_[0] = kFixed64;
}
void VariantParam::clear_fixed64() {
  if (has_fixed64()) {
    Value_.fixed64_ = GOOGLE_ULONGLONG(0);
    clear_has_Value();
  }
}
::google::protobuf::uint64 VariantParam::fixed64() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Fixed64)
  if (has_fixed64()) {
    return Value_.fixed64_;
  }
  return GOOGLE_ULONGLONG(0);
}
void VariantParam::set_fixed64(::google::protobuf::uint64 value) {
  if (!has_fixed64()) {
    clear_Value();
    set_has_fixed64();
  }
  Value_.fixed64_ = value;
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Fixed64)
}

// sfixed64 SFixed64 = 4;
bool VariantParam::has_sfixed64() const {
  return Value_case() == kSFixed64;
}
void VariantParam::set_has_sfixed64() {
  _oneof_case_[0] = kSFixed64;
}
void VariantParam::clear_sfixed64() {
  if (has_sfixed64()) {
    Value_.sfixed64_ = GOOGLE_LONGLONG(0);
    clear_has_Value();
  }
}
::google::protobuf::int64 VariantParam::sfixed64() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.SFixed64)
  if (has_sfixed64()) {
    return Value_.sfixed64_;
  }
  return GOOGLE_LONGLONG(0);
}
void VariantParam::set_sfixed64(::google::protobuf::int64 value) {
  if (!has_sfixed64()) {
    clear_Value();
    set_has_sfixed64();
  }
  Value_.sfixed64_ = value;
  // @@protoc_insertion_point(field_set:RPC.VariantParam.SFixed64)
}

// bool Bool = 5;
bool VariantParam::has_bool_() const {
  return Value_case() == kBool;
}
void VariantParam::set_has_bool_() {
  _oneof_case_[0] = kBool;
}
void VariantParam::clear_bool_() {
  if (has_bool_()) {
    Value_.bool__ = false;
    clear_has_Value();
  }
}
bool VariantParam::bool_() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Bool)
  if (has_bool_()) {
    return Value_.bool__;
  }
  return false;
}
void VariantParam::set_bool_(bool value) {
  if (!has_bool_()) {
    clear_Value();
    set_has_bool_();
  }
  Value_.bool__ = value;
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Bool)
}

// float Float = 6;
bool VariantParam::has_float_() const {
  return Value_case() == kFloat;
}
void VariantParam::set_has_float_() {
  _oneof_case_[0] = kFloat;
}
void VariantParam::clear_float_() {
  if (has_float_()) {
    Value_.float__ = 0;
    clear_has_Value();
  }
}
float VariantParam::float_() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Float)
  if (has_float_()) {
    return Value_.float__;
  }
  return 0;
}
void VariantParam::set_float_(float value) {
  if (!has_float_()) {
    clear_Value();
    set_has_float_();
  }
  Value_.float__ = value;
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Float)
}

// double Double = 7;
bool VariantParam::has_double_() const {
  return Value_case() == kDouble;
}
void VariantParam::set_has_double_() {
  _oneof_case_[0] = kDouble;
}
void VariantParam::clear_double_() {
  if (has_double_()) {
    Value_.double__ = 0;
    clear_has_Value();
  }
}
double VariantParam::double_() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Double)
  if (has_double_()) {
    return Value_.double__;
  }
  return 0;
}
void VariantParam::set_double_(double value) {
  if (!has_double_()) {
    clear_Value();
    set_has_double_();
  }
  Value_.double__ = value;
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Double)
}

// string String = 8;
bool VariantParam::has_string() const {
  return Value_case() == kString;
}
void VariantParam::set_has_string() {
  _oneof_case_[0] = kString;
}
void VariantParam::clear_string() {
  if (has_string()) {
    Value_.string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_Value();
  }
}
const ::std::string& VariantParam::string() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.String)
  if (has_string()) {
    return Value_.string_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
void VariantParam::set_string(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.String)
  if (!has_string()) {
    clear_Value();
    set_has_string();
    Value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPC.VariantParam.String)
}
#if LANG_CXX11
void VariantParam::set_string(::std::string&& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.String)
  if (!has_string()) {
    clear_Value();
    set_has_string();
    Value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPC.VariantParam.String)
}
#endif
void VariantParam::set_string(const char* value) {
  if (!has_string()) {
    clear_Value();
    set_has_string();
    Value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPC.VariantParam.String)
}
void VariantParam::set_string(const char* value, size_t size) {
  if (!has_string()) {
    clear_Value();
    set_has_string();
    Value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPC.VariantParam.String)
}
::std::string* VariantParam::mutable_string() {
  if (!has_string()) {
    clear_Value();
    set_has_string();
    Value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:RPC.VariantParam.String)
  return Value_.string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* VariantParam::release_string() {
  // @@protoc_insertion_point(field_release:RPC.VariantParam.String)
  if (has_string()) {
    clear_has_Value();
    return Value_.string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
void VariantParam::set_allocated_string(::std::string* string) {
  if (!has_string()) {
    Value_.string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_Value();
  if (string != NULL) {
    set_has_string();
    Value_.string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        string);
  }
  // @@protoc_insertion_point(field_set_allocated:RPC.VariantParam.String)
}

// string Decimal = 9;
bool VariantParam::has_decimal() const {
  return Value_case() == kDecimal;
}
void VariantParam::set_has_decimal() {
  _oneof_case_[0] = kDecimal;
}
void VariantParam::clear_decimal() {
  if (has_decimal()) {
    Value_.decimal_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_Value();
  }
}
const ::std::string& VariantParam::decimal() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Decimal)
  if (has_decimal()) {
    return Value_.decimal_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
void VariantParam::set_decimal(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Decimal)
  if (!has_decimal()) {
    clear_Value();
    set_has_decimal();
    Value_.decimal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.decimal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Decimal)
}
#if LANG_CXX11
void VariantParam::set_decimal(::std::string&& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Decimal)
  if (!has_decimal()) {
    clear_Value();
    set_has_decimal();
    Value_.decimal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.decimal_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPC.VariantParam.Decimal)
}
#endif
void VariantParam::set_decimal(const char* value) {
  if (!has_decimal()) {
    clear_Value();
    set_has_decimal();
    Value_.decimal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.decimal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPC.VariantParam.Decimal)
}
void VariantParam::set_decimal(const char* value, size_t size) {
  if (!has_decimal()) {
    clear_Value();
    set_has_decimal();
    Value_.decimal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.decimal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPC.VariantParam.Decimal)
}
::std::string* VariantParam::mutable_decimal() {
  if (!has_decimal()) {
    clear_Value();
    set_has_decimal();
    Value_.decimal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:RPC.VariantParam.Decimal)
  return Value_.decimal_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* VariantParam::release_decimal() {
  // @@protoc_insertion_point(field_release:RPC.VariantParam.Decimal)
  if (has_decimal()) {
    clear_has_Value();
    return Value_.decimal_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
void VariantParam::set_allocated_decimal(::std::string* decimal) {
  if (!has_decimal()) {
    Value_.decimal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_Value();
  if (decimal != NULL) {
    set_has_decimal();
    Value_.decimal_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        decimal);
  }
  // @@protoc_insertion_point(field_set_allocated:RPC.VariantParam.Decimal)
}

// bytes Bytes = 10;
bool VariantParam::has_bytes() const {
  return Value_case() == kBytes;
}
void VariantParam::set_has_bytes() {
  _oneof_case_[0] = kBytes;
}
void VariantParam::clear_bytes() {
  if (has_bytes()) {
    Value_.bytes_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_Value();
  }
}
const ::std::string& VariantParam::bytes() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Bytes)
  if (has_bytes()) {
    return Value_.bytes_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
void VariantParam::set_bytes(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Bytes)
  if (!has_bytes()) {
    clear_Value();
    set_has_bytes();
    Value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Bytes)
}
#if LANG_CXX11
void VariantParam::set_bytes(::std::string&& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Bytes)
  if (!has_bytes()) {
    clear_Value();
    set_has_bytes();
    Value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.bytes_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPC.VariantParam.Bytes)
}
#endif
void VariantParam::set_bytes(const char* value) {
  if (!has_bytes()) {
    clear_Value();
    set_has_bytes();
    Value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPC.VariantParam.Bytes)
}
void VariantParam::set_bytes(const void* value, size_t size) {
  if (!has_bytes()) {
    clear_Value();
    set_has_bytes();
    Value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPC.VariantParam.Bytes)
}
::std::string* VariantParam::mutable_bytes() {
  if (!has_bytes()) {
    clear_Value();
    set_has_bytes();
    Value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:RPC.VariantParam.Bytes)
  return Value_.bytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* VariantParam::release_bytes() {
  // @@protoc_insertion_point(field_release:RPC.VariantParam.Bytes)
  if (has_bytes()) {
    clear_has_Value();
    return Value_.bytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
void VariantParam::set_allocated_bytes(::std::string* bytes) {
  if (!has_bytes()) {
    Value_.bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_Value();
  if (bytes != NULL) {
    set_has_bytes();
    Value_.bytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        bytes);
  }
  // @@protoc_insertion_point(field_set_allocated:RPC.VariantParam.Bytes)
}

// bytes Guid = 11;
bool VariantParam::has_guid() const {
  return Value_case() == kGuid;
}
void VariantParam::set_has_guid() {
  _oneof_case_[0] = kGuid;
}
void VariantParam::clear_guid() {
  if (has_guid()) {
    Value_.guid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_Value();
  }
}
const ::std::string& VariantParam::guid() const {
  // @@protoc_insertion_point(field_get:RPC.VariantParam.Guid)
  if (has_guid()) {
    return Value_.guid_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
void VariantParam::set_guid(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Guid)
  if (!has_guid()) {
    clear_Value();
    set_has_guid();
    Value_.guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.guid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Guid)
}
#if LANG_CXX11
void VariantParam::set_guid(::std::string&& value) {
  // @@protoc_insertion_point(field_set:RPC.VariantParam.Guid)
  if (!has_guid()) {
    clear_Value();
    set_has_guid();
    Value_.guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.guid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPC.VariantParam.Guid)
}
#endif
void VariantParam::set_guid(const char* value) {
  if (!has_guid()) {
    clear_Value();
    set_has_guid();
    Value_.guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.guid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPC.VariantParam.Guid)
}
void VariantParam::set_guid(const void* value, size_t size) {
  if (!has_guid()) {
    clear_Value();
    set_has_guid();
    Value_.guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  Value_.guid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPC.VariantParam.Guid)
}
::std::string* VariantParam::mutable_guid() {
  if (!has_guid()) {
    clear_Value();
    set_has_guid();
    Value_.guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:RPC.VariantParam.Guid)
  return Value_.guid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* VariantParam::release_guid() {
  // @@protoc_insertion_point(field_release:RPC.VariantParam.Guid)
  if (has_guid()) {
    clear_has_Value();
    return Value_.guid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
void VariantParam::set_allocated_guid(::std::string* guid) {
  if (!has_guid()) {
    Value_.guid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_Value();
  if (guid != NULL) {
    set_has_guid();
    Value_.guid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        guid);
  }
  // @@protoc_insertion_point(field_set_allocated:RPC.VariantParam.Guid)
}

bool VariantParam::has_Value() const {
  return Value_case() != VALUE_NOT_SET;
}
void VariantParam::clear_has_Value() {
  _oneof_case_[0] = VALUE_NOT_SET;
}
VariantParam::ValueCase VariantParam::Value_case() const {
  return VariantParam::ValueCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcInvoke::kProxyIDFieldNumber;
const int RpcInvoke::kInterfaceIDFieldNumber;
const int RpcInvoke::kCallIDFieldNumber;
const int RpcInvoke::kDispIDFieldNumber;
const int RpcInvoke::kWFlagsFieldNumber;
const int RpcInvoke::kParamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcInvoke::RpcInvoke()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RPC_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.RpcInvoke)
}
RpcInvoke::RpcInvoke(const RpcInvoke& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      params_(from.params_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&proxyid_, &from.proxyid_,
    reinterpret_cast<char*>(&wflags_) -
    reinterpret_cast<char*>(&proxyid_) + sizeof(wflags_));
  // @@protoc_insertion_point(copy_constructor:RPC.RpcInvoke)
}

void RpcInvoke::SharedCtor() {
  ::memset(&proxyid_, 0, reinterpret_cast<char*>(&wflags_) -
    reinterpret_cast<char*>(&proxyid_) + sizeof(wflags_));
  _cached_size_ = 0;
}

RpcInvoke::~RpcInvoke() {
  // @@protoc_insertion_point(destructor:RPC.RpcInvoke)
  SharedDtor();
}

void RpcInvoke::SharedDtor() {
}

void RpcInvoke::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcInvoke::descriptor() {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[2].descriptor;
}

const RpcInvoke& RpcInvoke::default_instance() {
  protobuf_RPC_2eproto::InitDefaults();
  return *internal_default_instance();
}

RpcInvoke* RpcInvoke::New(::google::protobuf::Arena* arena) const {
  RpcInvoke* n = new RpcInvoke;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcInvoke::Swap(RpcInvoke* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcInvoke::InternalSwap(RpcInvoke* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RpcInvoke::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RpcInvoke

// sfixed32 ProxyID = 1;
void RpcInvoke::clear_proxyid() {
  proxyid_ = 0;
}
::google::protobuf::int32 RpcInvoke::proxyid() const {
  // @@protoc_insertion_point(field_get:RPC.RpcInvoke.ProxyID)
  return proxyid_;
}
void RpcInvoke::set_proxyid(::google::protobuf::int32 value) {
  
  proxyid_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcInvoke.ProxyID)
}

// fixed32 InterfaceID = 2;
void RpcInvoke::clear_interfaceid() {
  interfaceid_ = 0u;
}
::google::protobuf::uint32 RpcInvoke::interfaceid() const {
  // @@protoc_insertion_point(field_get:RPC.RpcInvoke.InterfaceID)
  return interfaceid_;
}
void RpcInvoke::set_interfaceid(::google::protobuf::uint32 value) {
  
  interfaceid_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcInvoke.InterfaceID)
}

// sfixed32 CallID = 3;
void RpcInvoke::clear_callid() {
  callid_ = 0;
}
::google::protobuf::int32 RpcInvoke::callid() const {
  // @@protoc_insertion_point(field_get:RPC.RpcInvoke.CallID)
  return callid_;
}
void RpcInvoke::set_callid(::google::protobuf::int32 value) {
  
  callid_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcInvoke.CallID)
}

// int32 DispID = 4;
void RpcInvoke::clear_dispid() {
  dispid_ = 0;
}
::google::protobuf::int32 RpcInvoke::dispid() const {
  // @@protoc_insertion_point(field_get:RPC.RpcInvoke.DispID)
  return dispid_;
}
void RpcInvoke::set_dispid(::google::protobuf::int32 value) {
  
  dispid_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcInvoke.DispID)
}

// int32 wFlags = 5;
void RpcInvoke::clear_wflags() {
  wflags_ = 0;
}
::google::protobuf::int32 RpcInvoke::wflags() const {
  // @@protoc_insertion_point(field_get:RPC.RpcInvoke.wFlags)
  return wflags_;
}
void RpcInvoke::set_wflags(::google::protobuf::int32 value) {
  
  wflags_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcInvoke.wFlags)
}

// repeated .RPC.VariantParam Params = 6;
int RpcInvoke::params_size() const {
  return params_.size();
}
void RpcInvoke::clear_params() {
  params_.Clear();
}
const ::RPC::VariantParam& RpcInvoke::params(int index) const {
  // @@protoc_insertion_point(field_get:RPC.RpcInvoke.Params)
  return params_.Get(index);
}
::RPC::VariantParam* RpcInvoke::mutable_params(int index) {
  // @@protoc_insertion_point(field_mutable:RPC.RpcInvoke.Params)
  return params_.Mutable(index);
}
::RPC::VariantParam* RpcInvoke::add_params() {
  // @@protoc_insertion_point(field_add:RPC.RpcInvoke.Params)
  return params_.Add();
}
::google::protobuf::RepeatedPtrField< ::RPC::VariantParam >*
RpcInvoke::mutable_params() {
  // @@protoc_insertion_point(field_mutable_list:RPC.RpcInvoke.Params)
  return &params_;
}
const ::google::protobuf::RepeatedPtrField< ::RPC::VariantParam >&
RpcInvoke::params() const {
  // @@protoc_insertion_point(field_list:RPC.RpcInvoke.Params)
  return params_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcReturn_ExceptionInfo::kDescriptionFieldNumber;
const int RpcReturn_ExceptionInfo::kScodeFieldNumber;
const int RpcReturn_ExceptionInfo::kWCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcReturn_ExceptionInfo::RpcReturn_ExceptionInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RPC_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.RpcReturn.ExceptionInfo)
}
RpcReturn_ExceptionInfo::RpcReturn_ExceptionInfo(const RpcReturn_ExceptionInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.description().size() > 0) {
    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  ::memcpy(&scode_, &from.scode_,
    reinterpret_cast<char*>(&wcode_) -
    reinterpret_cast<char*>(&scode_) + sizeof(wcode_));
  // @@protoc_insertion_point(copy_constructor:RPC.RpcReturn.ExceptionInfo)
}

void RpcReturn_ExceptionInfo::SharedCtor() {
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&scode_, 0, reinterpret_cast<char*>(&wcode_) -
    reinterpret_cast<char*>(&scode_) + sizeof(wcode_));
  _cached_size_ = 0;
}

RpcReturn_ExceptionInfo::~RpcReturn_ExceptionInfo() {
  // @@protoc_insertion_point(destructor:RPC.RpcReturn.ExceptionInfo)
  SharedDtor();
}

void RpcReturn_ExceptionInfo::SharedDtor() {
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RpcReturn_ExceptionInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcReturn_ExceptionInfo::descriptor() {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[3].descriptor;
}

const RpcReturn_ExceptionInfo& RpcReturn_ExceptionInfo::default_instance() {
  protobuf_RPC_2eproto::InitDefaults();
  return *internal_default_instance();
}

RpcReturn_ExceptionInfo* RpcReturn_ExceptionInfo::New(::google::protobuf::Arena* arena) const {
  RpcReturn_ExceptionInfo* n = new RpcReturn_ExceptionInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcReturn_ExceptionInfo::Swap(RpcReturn_ExceptionInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcReturn_ExceptionInfo::InternalSwap(RpcReturn_ExceptionInfo* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RpcReturn_ExceptionInfo::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[3];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RpcReturn_ExceptionInfo

// string Description = 1;
void RpcReturn_ExceptionInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& RpcReturn_ExceptionInfo::description() const {
  // @@protoc_insertion_point(field_get:RPC.RpcReturn.ExceptionInfo.Description)
  return description_.GetNoArena();
}
void RpcReturn_ExceptionInfo::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RPC.RpcReturn.ExceptionInfo.Description)
}
#if LANG_CXX11
void RpcReturn_ExceptionInfo::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RPC.RpcReturn.ExceptionInfo.Description)
}
#endif
void RpcReturn_ExceptionInfo::set_description(const char* value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RPC.RpcReturn.ExceptionInfo.Description)
}
void RpcReturn_ExceptionInfo::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RPC.RpcReturn.ExceptionInfo.Description)
}
::std::string* RpcReturn_ExceptionInfo::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:RPC.RpcReturn.ExceptionInfo.Description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* RpcReturn_ExceptionInfo::release_description() {
  // @@protoc_insertion_point(field_release:RPC.RpcReturn.ExceptionInfo.Description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RpcReturn_ExceptionInfo::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:RPC.RpcReturn.ExceptionInfo.Description)
}

// int32 scode = 2;
void RpcReturn_ExceptionInfo::clear_scode() {
  scode_ = 0;
}
::google::protobuf::int32 RpcReturn_ExceptionInfo::scode() const {
  // @@protoc_insertion_point(field_get:RPC.RpcReturn.ExceptionInfo.scode)
  return scode_;
}
void RpcReturn_ExceptionInfo::set_scode(::google::protobuf::int32 value) {
  
  scode_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcReturn.ExceptionInfo.scode)
}

// int32 wCode = 3;
void RpcReturn_ExceptionInfo::clear_wcode() {
  wcode_ = 0;
}
::google::protobuf::int32 RpcReturn_ExceptionInfo::wcode() const {
  // @@protoc_insertion_point(field_get:RPC.RpcReturn.ExceptionInfo.wCode)
  return wcode_;
}
void RpcReturn_ExceptionInfo::set_wcode(::google::protobuf::int32 value) {
  
  wcode_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcReturn.ExceptionInfo.wCode)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcReturn::kCallIDFieldNumber;
const int RpcReturn::kHResultFieldNumber;
const int RpcReturn::kReturnValFieldNumber;
const int RpcReturn::kExceptionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcReturn::RpcReturn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_RPC_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RPC.RpcReturn)
}
RpcReturn::RpcReturn(const RpcReturn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_returnval()) {
    returnval_ = new ::RPC::VariantParam(*from.returnval_);
  } else {
    returnval_ = NULL;
  }
  if (from.has_exception()) {
    exception_ = new ::RPC::RpcReturn_ExceptionInfo(*from.exception_);
  } else {
    exception_ = NULL;
  }
  ::memcpy(&callid_, &from.callid_,
    reinterpret_cast<char*>(&hresult_) -
    reinterpret_cast<char*>(&callid_) + sizeof(hresult_));
  // @@protoc_insertion_point(copy_constructor:RPC.RpcReturn)
}

void RpcReturn::SharedCtor() {
  ::memset(&returnval_, 0, reinterpret_cast<char*>(&hresult_) -
    reinterpret_cast<char*>(&returnval_) + sizeof(hresult_));
  _cached_size_ = 0;
}

RpcReturn::~RpcReturn() {
  // @@protoc_insertion_point(destructor:RPC.RpcReturn)
  SharedDtor();
}

void RpcReturn::SharedDtor() {
  if (this != internal_default_instance()) {
    delete returnval_;
  }
  if (this != internal_default_instance()) {
    delete exception_;
  }
}

void RpcReturn::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcReturn::descriptor() {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[4].descriptor;
}

const RpcReturn& RpcReturn::default_instance() {
  protobuf_RPC_2eproto::InitDefaults();
  return *internal_default_instance();
}

RpcReturn* RpcReturn::New(::google::protobuf::Arena* arena) const {
  RpcReturn* n = new RpcReturn;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcReturn::Swap(RpcReturn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcReturn::InternalSwap(RpcReturn* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RpcReturn::GetMetadata() const {
  protobuf_RPC_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_RPC_2eproto::file_level_metadata[4];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RpcReturn

// sfixed32 CallID = 1;
void RpcReturn::clear_callid() {
  callid_ = 0;
}
::google::protobuf::int32 RpcReturn::callid() const {
  // @@protoc_insertion_point(field_get:RPC.RpcReturn.CallID)
  return callid_;
}
void RpcReturn::set_callid(::google::protobuf::int32 value) {
  
  callid_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcReturn.CallID)
}

// sfixed32 HResult = 2;
void RpcReturn::clear_hresult() {
  hresult_ = 0;
}
::google::protobuf::int32 RpcReturn::hresult() const {
  // @@protoc_insertion_point(field_get:RPC.RpcReturn.HResult)
  return hresult_;
}
void RpcReturn::set_hresult(::google::protobuf::int32 value) {
  
  hresult_ = value;
  // @@protoc_insertion_point(field_set:RPC.RpcReturn.HResult)
}

// .RPC.VariantParam ReturnVal = 3;
bool RpcReturn::has_returnval() const {
  return this != internal_default_instance() && returnval_ != NULL;
}
void RpcReturn::clear_returnval() {
  if (GetArenaNoVirtual() == NULL && returnval_ != NULL) delete returnval_;
  returnval_ = NULL;
}
const ::RPC::VariantParam& RpcReturn::returnval() const {
  // @@protoc_insertion_point(field_get:RPC.RpcReturn.ReturnVal)
  return returnval_ != NULL ? *returnval_
                         : *::RPC::VariantParam::internal_default_instance();
}
::RPC::VariantParam* RpcReturn::mutable_returnval() {
  
  if (returnval_ == NULL) {
    returnval_ = new ::RPC::VariantParam;
  }
  // @@protoc_insertion_point(field_mutable:RPC.RpcReturn.ReturnVal)
  return returnval_;
}
::RPC::VariantParam* RpcReturn::release_returnval() {
  // @@protoc_insertion_point(field_release:RPC.RpcReturn.ReturnVal)
  
  ::RPC::VariantParam* temp = returnval_;
  returnval_ = NULL;
  return temp;
}
void RpcReturn::set_allocated_returnval(::RPC::VariantParam* returnval) {
  delete returnval_;
  returnval_ = returnval;
  if (returnval) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:RPC.RpcReturn.ReturnVal)
}

// .RPC.RpcReturn.ExceptionInfo Exception = 4;
bool RpcReturn::has_exception() const {
  return this != internal_default_instance() && exception_ != NULL;
}
void RpcReturn::clear_exception() {
  if (GetArenaNoVirtual() == NULL && exception_ != NULL) delete exception_;
  exception_ = NULL;
}
const ::RPC::RpcReturn_ExceptionInfo& RpcReturn::exception() const {
  // @@protoc_insertion_point(field_get:RPC.RpcReturn.Exception)
  return exception_ != NULL ? *exception_
                         : *::RPC::RpcReturn_ExceptionInfo::internal_default_instance();
}
::RPC::RpcReturn_ExceptionInfo* RpcReturn::mutable_exception() {
  
  if (exception_ == NULL) {
    exception_ = new ::RPC::RpcReturn_ExceptionInfo;
  }
  // @@protoc_insertion_point(field_mutable:RPC.RpcReturn.Exception)
  return exception_;
}
::RPC::RpcReturn_ExceptionInfo* RpcReturn::release_exception() {
  // @@protoc_insertion_point(field_release:RPC.RpcReturn.Exception)
  
  ::RPC::RpcReturn_ExceptionInfo* temp = exception_;
  exception_ = NULL;
  return temp;
}
void RpcReturn::set_allocated_exception(::RPC::RpcReturn_ExceptionInfo* exception) {
  delete exception_;
  exception_ = exception;
  if (exception) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:RPC.RpcReturn.Exception)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace RPC

// @@protoc_insertion_point(global_scope)
